username: "{{ env.WP_USERNAME }}"
password: "{{ env.WP_PASSWORD }}"
base_url: "{{ env.WP_BASE_URL }}"
start_date: "{{ env.WP_START_DATE }}"
include_categories: "{{ env.WP_INCLUDE_CATEGORIES }}"
include_comments: "{{ env.WP_INCLUDE_COMMENTS }}"
include_media: "{{ env.WP_INCLUDE_MEDIA }}"
api_version: "{{ env.WP_API_VERSION }}"
auth_type: "{{ env.WP_AUTH_TYPE }}"
